[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "9ri4ddvn5PVouDM1eX4KhCo4a3SAcrNKyKgunKce43Gm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/konstantina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
